apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment
spec:
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: adityanair006/micro-comments
          env:
            - name: EVENT_BUS_ADDRESS
              value: "event-bus-service.default"
