apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: adityanair006/micro-posts
          env:
            - name: EVENT_BUS_ADDRESS
              value: "event-bus-service.default"
