apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
spec:
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: adityanair006/micro-query
          env:
            - name: EVENT_BUS_ADDRESS
              value: "event-bus-service.default"
